version: '2'
services:
  reformedacademy:
    build: .
    ports:
      - "80:80"
    environment:
      DJANGO_SETTINGS_MODULE: reformedacademy.local_settings
      SERVER_ENVIRONMENT: prod
    volumes:
      - ./:/code
