version: '2'
services:
  reformedacademy:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: reformedacademy.local_settings
    volumes:
      - ./:/home/docker/code
