db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_USER: "root"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "reformedacademy"
    volumes:
        - ./sql:/docker-entrypoint-initdb.d